services:
  front:
    image: front-app
    build: ./front-end
    restart: always
    ports:
     - "3000:3000"
    deploy:
        mode: replicated
        replicas: 1

  broker-service:
    image: broker-api
    build: ./broker-service 
    restart: always
    ports:
    # can hit broker-service on port 8080 from frontend at port 80
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1
  
