services:
  front:
    image: front-app
    build: ./front-end
    restart: always
    # port host:docker
    ports:
     - "3000:3000"
    deploy:
        mode: replicated
        replicas: 1

  broker-service:
    image: broker-api
    build: ./broker-service 
    restart: always
    ports:
      - "3001:3000"
    deploy:
      mode: replicated
      replicas: 1
  
  auth-service:
    image: auth-api
    build: ./auth-service 
    restart: always
    ports:
      - "3002:3000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5" 
  postgres:
    image: postgres:14.0
    ports: 
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  
