services:
  broker-service:
    build: 
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    ports:
    # can hit broker-service on port 8080 from frontend at port 80
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1