services:
  front:
    image: front-app
    build: ./front-end
    restart: always
    # port host:docker
    ports:
     - "3000:3000"
    deploy:
        mode: replicated
        replicas: 1

  mailer-service:
    image: mailer-api
    build: ./mailer-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM_NAME: "John Smith"
      MAIL_FROM_ADDRESS;: "john.smith@example.com"
  broker-service:
    image: broker-api
    build: ./broker-service 
    restart: always
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1
  logger-service:
   image: logger-api
   build: ./logger-service
   restart: always
   ports:
     - "3003:3003"
   deploy:
     mode: replicated
     replicas: 1
  auth-service:
    image: auth-api
    build: ./auth-service 
    restart: always
    ports:
      - "3002:3002"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5" 
  postgres:
    image: postgres:14.0
    ports: 
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  
  mongo:
    image: docker.arvancloud.ir/mongo:latest
    ports: 
      - "27017:27017"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025" # web interface
    deploy:
      mode: replicated
      replicas: 1
